---
title: "Prayer Guide for New Muslims" 
subtitle: "Presented by the London Central Mosque Trust & The Islamic Cultural Centre"
---

## Welcome {.unnumbered}

This course is designed for **new Muslims** and for anyone who wants to **refresh their understanding of Salah (the prayer)**.

We created this course at the London Central Mosque because many of the resources available today on videos, booklets and blogs can be overwhelming.

They often include:

-   Too many **Sunnah (recommended)** actions, which are not required for the Salah to be valid. <!--# Are we sure? Sounds too dismissive of the others... Maybe soften it up or combine with the last point -->
-   Content exclusively in **Arabic**, which can make learning feel difficult and discouraging for non-Arabic speakers.
-   A lack of clear structure where many do not explain the difference between what’s **essential** and what’s **optional**, or how to build up your Salah step by step.

As a result, learning how to pray can feel confusing or take much longer than it should.

## What Makes This Course Different? {.unnumbered}

We focus on keeping it simple, practical and spiritually meaningful.

In this course, you will:

1.  Learn the **pillars and required actions** of the Salah, what you need to do for your Salah to be valid.
2.  Learn how to recite **Surat Al-Fatihah**, the essential chapter in every unit of Salah plus and **Tashahud** which is essential also.
3.  Understand the **basic rules** related to Salah like cleanliness, direction, timing and join a congregation.
4.  Discover the spiritual meaning of Salah like how it connects you with your Creator and brings peace to the heart.

Once you’ve learned the basics, you’ll be in a strong position to gradually add more **Sunnah practices** and deepen your Salah over time.

We hope this course helps you feel confident in your Salah and brings you closer to Allah, InShaAllah.

## Course Outline {.unnumbered}

The topics covered are:

| Section | Topic                                                     |
|:--------|:----------------------------------------------------------|
| 1       | [Importance of Salah]({{< var urls.u01 >}})               |
| 1       | [Conditions/Prerequisites of Salah]({{< var urls.u02 >}}) |
| 2       | [Pillars of Salah]({{< var urls.u03 >}})                  |
| 2       | [Obligatory Acts of Salah]({{< var urls.u04 >}})          |
| 2       | [Salah Demonstrated]({{< var urls.u05 >}})                |
| 3       | [Rulings Related to Salah]({{< var urls.u06 >}})          |
| 3       | [Recommended Actions]({{< var urls.u07 >}})               |

## Acknowledgements {.unnumbered}

Sh Ali Ruwaiba as the lead-author... Dr Shunya Kimura and James Sampson as the editor...

This workbook is created using the [Quarto](https://quarto.org/) publishing system. Elements of this workbook are partially based on and modified from:

-   INSERT ANY MATERIAL HERE

This year's workbook takes inspiration and design elements from:

-   The [GEOG0030: Geocomputation 2023-2024](https://jtvandijk.github.io/GEOG0030_20232024/) workbook by [Justin van Dijk](https://www.mappingdutchman.com)
