---
title: "Pillars and Obligatory Acts"
---

In salah, **pillars (fard 'ayn)** are essential actions that invalidate the prayer if omitted, whether intentionally or unintentionally. **Obligatory acts (wajib)** are also necessary, but if forgotten, they can be compensated for by performing the prostrations of forgetfulness (*sujood as-sahw*).

::: callout-note
The third category is **Sunnah acts**, which are recommended but not mandatory. They enhance the prayer but do not invalidate it if omitted. More on @sec-act-pillars .
:::

## Pillars {#sec-act-pillars}

These are the 14 fundamental components of salah:

1.  Standing during obligatory salaat (only if you are able)

2.  The opening Takbir *(*saying '*Allahu Akbar')*

    {{< audio file="assets/takbir.mp3">}}

3.  Reciting Surah al-Fatihah

    {{< video file="assets/surah-al-fatihah.mp4">}}

4.  Ruku (bowing)

5.  Rising from Ruku

6.  Standing up straight

7.  Sujood (prostration)

8.  Rising from Sujood

9.  Sitting between the two prostrations

10. Saying the final Tahahhud

    |  |  |
    |----|----|
    | Attaḥiyyātu lillāhi waṣṣalawātu, waṭṭayyibāt, assalāmu alayka 'ayyuhan-Nabiyyu wa raḥmatullāhi wa barakātuh, assalāmualaynā wa alā ‘ibādillāhiṣ-ṣāliḥīn. 'Ash-hadu 'an lā 'ilāha 'illallāh wa 'ash-hadu 'anna Muḥammadanabduhu wa rasūluh. | All greetings of humility are for Allah, and all prayers and goodness. Peace be upon you, O Prophet, and the mercy of Allah and His blessings. Peace be upon us and upon the righteous slaves of Allah. I bear witness that there is none worthy of worship but Allah, and I bear witness that Muhammad is His slave and His Messenger. |

    {{< audio file="assets/tashahhud.mp3" caption="">}}

11. Sitting for the final tahahhud and the salaams

12. The two salaams

13. Doing these pillars in order

14. Being at ease in each of the physical pillars

## Obligatory Acts

These are the eight components of salah:

1.  All the Takbirs other than the opening Takbir.

2.  Saying "*Sami a Allahu liman hamidah* (Allah hears those who praise Him)"

    {{< audio file="assets/obligatory-2.mp3" caption="">}}

3.  Saying "*Rabbana wa laka l-hamd* (Our Lord, to You be praise)"

    {{< audio file="assets/obligatory-3.mp3" caption="">}}

4.  Saying "*Subhaana rabbiy al- adheem* (Glory be to my Lord Almighty)" once when bowing

    {{< audio file="assets/obligatory-4.mp3" caption="">}}

5.  Saying "*Subhaana rabbiy al-a laa* (Glory be to my Lord most High)" once when prostrating

    {{< audio file="assets/obligatory-5.mp3" caption="">}}

6.  Saying "*Rabbighfir li* (Lord forgive me)" between the two prostration

    {{< audio file="assets/obligatory-6.mp3" caption="">}}

7.  Saying the first tashahhud

8.  Sitting for the first tashahhud

::: callout-note
See the above in action in @sec-two-units-demo .
:::

## What if I Miss a Pillar or Obligatory Act?

## What if I Can't Remember the Words?

<https://sunnah.com/abudawud:861>

### Replacement of Surah al-Fatihah

### Replacement of Tashahhud
